jdk:
  - oraclejdk7
services:
  - mongodb
env:
  - DISPLAY=:99.0
before_install:
  - "./fetchIdea.sh"
  - mongo -- version
  - sh -e /etc/init.d/xvfb start
script: "./travis.sh"
cache:
  directories:
  - idea-IC
